# build stage
FROM node:20.19.2 AS build-stage
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --non-interactive --ignore-scripts
COPY . .
RUN yarn run build:dev

# production stage
FROM nginx:stable-alpine

ARG ARG_BRANCH
ARG ARG_VERSION
ARG ARG_TAG
ARG ARG_ENV
ARG ARG_BUILD_DATE

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

ENV APP_BRANCH=${ARG_BRANCH} \
    APP_VERSION=${ARG_VERSION} \
    APP_TAG=${ARG_TAG} \
    APP_ENV=${ARG_ENV} \
    APP_BUILD_DATE=${ARG_BUILD_DATE}

