const ACCESS_TOKEN_KEY = 'access_token';
const REFRESH_TOKEN_KEY = 'refresh_token';

const DATE_FORMAT_DDMMYYYY = 'DD/MM/YYYY';
const DATETIME_FORMAT_DDMMYYYY_HHMMSS = 'DD/MM/YYYY HH:mm:ss';

export {
  ACCESS_TOKEN_KEY,
  REFRESH_TOKEN_KEY,
  DATE_FORMAT_DDMMYYYY,
  DATETIME_FORMAT_DDMMYYYY_HHMMSS,
};
