const GET_ALL_CENTER_QUERY_KEY = 'GET_ALL_CENTERS';

const GET_CENTER_DETAIL_QUERY_KEY = 'GET_CENTER_DETAIL';

const GET_USER_LIST_QUERY_KEY = 'GET_USER_LIST';

const GET_REFERENCE_BY_PROJECT_QUERY_KEY = 'GET_REFERENCE_BY_PROJECT';

const GET_USER_INFO_QUERY_KEY = 'GET_USER_INFO';

export {
  GET_ALL_CENTER_QUERY_KEY,
  GET_CENTER_DETAIL_QUERY_KEY,
  GET_USER_LIST_QUERY_KEY,
  GET_REFERENCE_BY_PROJECT_QUERY_KEY,
  GET_USER_INFO_QUERY_KEY,
};
