const GET_ALL_RESTAURANT_QUERY_KEY = 'GET_ALL_RESTAURANTS';

const GET_RESTAURANT_DETAIL_QUERY_KEY = 'GET_RESTAURANT_DETAIL';

export { GET_ALL_RESTAURANT_QUERY_KEY, GET_RESTAURANT_DETAIL_QUERY_KEY };
