const GET_ALL_RESTAURANT_QUERY_KEY = 'GET_ALL_RESTAURANTS';

const GET_RESTAURANT_DETAIL_QUERY_KEY = 'GET_RESTAURANT_DETAIL';

const GET_VIDEOS_UPLOADED_QUERY_KEY = 'GET_VIDES_UPLOADED';

export {
  GET_ALL_RESTAURANT_QUERY_KEY,
  GET_RESTAURANT_DETAIL_QUERY_KEY,
  GET_VIDEOS_UPLOADED_QUERY_KEY,
};
